SELECT (CAST(SUBSTRING(VALUE, 5, 2) AS INT) * 3600000) + 
(CAST(SUBSTRING(VALUE, 8, 2) AS INT) * 60000) + 
(CAST(SUBSTRING(VALUE, 11, 2) AS INT) * 1000) AS milliseconds 
FROM V$DATAGUARD_STATS 
WHERE NAME='APPLY_FINISH_TIME' 
ORDER BY CAST(TIME_COMPUTED AS DATETIME) 
DESC LIMIT 1;




SELECT (CAST(SUBSTRING(VALUE, 5, 2) AS INT) * 3600000) + 
(CAST(SUBSTRING(VALUE, 8, 2) AS INT) * 60000) + 
(CAST(SUBSTRING(VALUE, 11, 2) AS INT) * 1000) AS milliseconds 
FROM V$DATAGUARD_STATS 
WHERE NAME='APPLY_LAG' 
ORDER BY CAST(TIME_COMPUTED AS DATETIME)
DESC LIMIT 1;




SELECT (CAST(SUBSTRING(VALUE, 5, 2) AS INT) * 3600000) + 
(CAST(SUBSTRING(VALUE, 8, 2) AS INT) * 60000) + 
(CAST(SUBSTRING(VALUE, 11, 2) AS INT) * 1000) AS milliseconds 
FROM V$DATAGUARD_STATS 
WHERE NAME='TRANSPORT_LAG' 
ORDER BY CAST(TIME_COMPUTED AS DATETIME) 
DESC LIMIT 1;