CREATE TABLE table_name (
    column1 datatype,
    column1 datatype,
)

CREATE TABLE V$DATAGUARD_STATS (
    SOURCE_DBID NUMBER,
    SOURCE_DB_UNIQUE_NAME VARCHAR2(32),
    NAME VARCHAR2(32),
    VALUE VARCHAR2(64),
    UNIT VARCHAR2(30),
    TIME_COMPUTED VARCHAR2(30),
    DATUM_TIME VARCHAR2(30),
    CON_ID NUMBER
)